# Site settings
title: 진지한 난장판 V3
url: "https://neoarc.github.io"
baseurl: ""
description: >
    neoarc blog - powered by johngrib wiki

# My information
email: neoarcturus@gmail.com
author: neoarc
profile: ...
# twitter_username: John_Grib
github_username: neoarc
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
disqus:
  id: neoarc
  shortname: neoarc
utterances:
  repo: neoarc/neoarc.github.io
  issue-term: pathname
  label: Comment
  branch: master

# google_analytics:
#  ua: UA-110224147-1

google_adsense:
  client: ca-pub-3901831903106648

blame: "https://github.com/neoarc/neoarc.github.io/blame/master/_wiki"
edit: "https://github.com/neoarc/neoarc.github.io/edit/master/_wiki"
issue: "https://github.com/neoarc/neoarc.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
