google_translator:
    - {fileName: my_wiki_google_translator}
gadget:
    - {fileName: my_wiki_google_translator}
my_project:
    - {fileName: NaMacroJS}
    - {fileName: sfmb}
macro:
    - {fileName: NaMacroJS}
utility:
    - {fileName: power_automate_desktop}
automation:
    - {fileName: power_automate_desktop}
sfmb:
    - {fileName: sfmb}
잡담:
    - {fileName: sleepy_moment}
idle_talk:
    - {fileName: sleepy_moment}
wiki:
    - {fileName: wiki_i_have_tried}
    - {fileName: wiki_on_github_io}
github.io:
    - {fileName: wiki_on_github_io}
vimwiki:
    - {fileName: wiki_on_github_io}
jekyll:
    - {fileName: wiki_on_github_io}
