my_project:
    - {fileName: about_neoarc_macro_js}
    - {fileName: about_super_fanmade_mario_bros}
macro:
    - {fileName: about_neoarc_macro_js}
자동화:
    - {fileName: about_neoarc_macro_js}
    - {fileName: power_automate_desktop}
매크로:
    - {fileName: about_neoarc_macro_js}
sfmb:
    - {fileName: about_super_fanmade_mario_bros}
    - {fileName: sfmb_exp_and_coin_table}
    - {fileName: sfmb_trouble_shooting}
    - {fileName: sfmb_tutorial}
    - {fileName: sfmb_version_history}
악성코드:
    - {fileName: i_found_unknown_malware}
google_translator:
    - {fileName: my_wiki_google_translator}
gadget:
    - {fileName: my_wiki_google_translator}
wiki:
    - {fileName: my_wiki_todolist}
    - {fileName: wiki_i_have_tried}
    - {fileName: wiki_on_github_io}
johngrib_wiki:
    - {fileName: my_wiki_todolist}
utility:
    - {fileName: power_automate_desktop}
automation:
    - {fileName: power_automate_desktop}
유틸리티:
    - {fileName: power_automate_desktop}
sfmb_betatest:
    - {fileName: sfmb_how_to_make_parallax_background}
잡담:
    - {fileName: sleepy_moment}
idle_talk:
    - {fileName: sleepy_moment}
github.io:
    - {fileName: wiki_on_github_io}
vimwiki:
    - {fileName: wiki_on_github_io}
jekyll:
    - {fileName: wiki_on_github_io}
